trigger:
- master
- release/*

pool:
  vmImage: windows-latest

variables:
- group: npm-tokens

steps:
- checkout: self
  clean: true

- task: NodeTool@0
  displayName: Use node 10
  inputs:
    versionSpec: "10.x"

- script: npm i -g npm@6.14.12 --force
  displayName: Use npm version 6.14.12

- script: | 
    npm ci
    npm run build
  displayName: Build TFX CLI

- ${{ if in(variables['build.reason'], 'IndividualCI', 'BatchedCI') }}:
  # For CI runs on master, automatically publish packages
  - bash: |
      echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      npm publish
      rm .npmrc
    displayName: Publish TFX CLI
    continueOnError: true
    condition: succeeded()
    env:
      NPM_TOKEN: $(npm-automation.token)

  - bash: |
      npm pack
      cp *.tgz '$(Build.ArtifactStagingDirectory)'
    displayName: Pack
    condition: succeeded()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactType: 'pipeline'
      artifactName: 'tfx-cli-package'
    condition: succeeded()
